### ISSUE TITLE
After running app, build command never completes on Windows (and left behind a ~3GB zip file)

### ISSUE THREAD

**Issue by jaredkrinke** [neutralinojs/neutralinojs-cli#91] opened 2022-01-07 04:33 UTC
Note: This is my very first experience with Neutralino and I'm just following the [the docs](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app). I didn't see an existing bug for this.

**Expected Behavior**  
Build command creates a zip file with the sample app, ready for distribution.
  
**Actual Behavior**  
The command never completed. I ended up killing it after a few minutes and it left a ~3GB zip file in the `dist` folder.

Output:
```
Bundling app...
Generating resources.neu...
Copying binaries...
Making app bundle ZIP file...
```

**Steps to Reproduce the Problem**  
1. `npm install @neutralinojs/neu`
2. `npx @neutralinojs/neu create .`
3. `npx @neutralinojs/neu run`
4. Close the running app
5. `npx @neutralinojs/neu build --release`

NOTE: if I skip the "run and close" steps, then the app builds fine.

**Specifications**  
* NeutralinoJs Version: Neutralinojs binaries: v4.0.0, Neutralinojs client: v3.0.0
* NeutralinoJs CLI version: v8.1.0
* Platform: Windows 20H2 x64

**Comment by pathange-s** [comment] 2022-03-10 17:44
@jaredkrinke Tried to follow the steps to reproduce the issue. But, It worked fine. The release build file is produced without any issue. Also, the file sizes produced were considerable. Can someone confirm if they are able to reproduce the issue ? If its working fine, lets close it to reduce unwanted issues.

CC : @shalithasuranga @DEVLOPRR

**Comment by pathange-s** [comment] 2022-03-10 17:57
@jaredkrinke Got a windows, and tried to follow the steps to reproduce the issue. But, It worked fine. The release build file is produced without any issue. Also, the file sizes produced were considerable and normal.
Can someone confirm if they are able to reproduce the issue ? If its working fine, lets close it.

CC : @shalithasuranga @DEVLOPRR

**Comment by DEVLOPRR** [comment] 2022-03-10 18:07
This problem doesn't occur, possible reasons are the folder you've specified in `resourcePath` contains node_modules folder or some unnecessary files. It would be great if you shared your directory structure.

**Comment by jaredkrinke** [comment] 2022-03-10 21:29
Feel free to close if no one else has this problem. Someone else can reopen the bug in the future if they hit it.

For reference:

* The directory structure is just whatever the scaffolding command creates
* Everything was in a subdirectory of my user folder (C:\Users\jared\code\test).

**Comment by jaredkrinke** [comment] 2022-03-11 22:56
I wouldn't waste time digging into this unless someone else reports the same problem. I don't think my machine has anything unusual going on, but if I'm the only one hitting this, it doesn't seem that important.

But for reference, yes, this still happens to me on:

```
--- Global ---
neu CLI: v9.2.0

--- Project: . (js.neutralino.sample) ---
Neutralinojs binaries: v4.4.0
Neutralinojs client: v3.3.0
Project version: v1.0.0
```

**Comment by DEVLOPRR** [comment] 2022-03-11 23:16
## Issue Verified
This issue has been verified and is a valid issue, tested this on Linux and this occurs there too.

## Reason
The Reason is the way neutralino cli handles path, when you create a new app with `.`, this causes some weird bugs.

Note that the command `neu create appName` takes the application name instead of the path.

## End
We are looking forward for a clear reason why this occurs in the code itself, and a patch will be released soon!

# Thanks

**Comment by viralgupta** [comment] 2024-03-07 19:35
@shalithasuranga, we can close this issue as i couldn't reproduce it, likely because a patch has already been issued.

**Comment by shalithasuranga** [comment] 2024-05-06 13:08
@viralgupta Sure, we can re-open this issue again if another Neutralinojs developer can reproduce this problem. Thanks so much everyone for working on this :tada:

**Closed by shalithasuranga** 2024-05-06 13:08 UTC
