### ISSUE TITLE
No errors in terminal while running app with --frontend-lib-dev flag with development server not up

### ISSUE THREAD

**Issue by pathange-s** [neutralinojs/neutralinojs-cli#124] opened 2022-03-26 04:26 UTC
### Actual Behaviour
- When the development server is not started and we run `neu run --frontend-lib-dev` the app doesnt function and shows `Could not connect: Connection refused`

### Expected Behaviour
- The application must throw an error in the terminal and the app must exit with respective exit code

![image](https://user-images.githubusercontent.com/76244077/160224610-0f389134-2c5a-4b8d-a9fe-05fb545386fe.png)

This issue occurs on all OS with any `neu cli version`

P.S. Disucussed this with @shalithasuranga and @DEVLOPRR . Was told that developers will be able to figure it out. Opening this issue to make developers can have it noted and to sure we keep it noted and implement fix whenever required

**Comment by DEVLOPRR** [comment] 2022-03-26 23:59
Exiting is not a option as people are usually using packages like `concurrently` to run there frontend library bundler and NeutralinoJs side by side, causing it to exit can cause inconvenience.

**Comment by pathange-s** [comment] 2022-03-27 05:17
Noted ! Lets make sure that if this is getting a fix, it doesn't do this fault.

**Comment by YashKumarVerma** [comment] 2022-04-03 19:26
Should we create a new list of known issues in place of keeping it in the `active` / `open` category? 

> P.S. Disucussed this with @shalithasuranga and @DEVLOPRR . Was told that developers will be able to figure it out. 

from this it appears it is not getting a fix in near future.

**Comment by shalithasuranga** [comment] 2023-10-28 06:24
Hi all.. thanks for reporting and discussing this. Now, the CLI will wait for the sepecific development server URL's port and open the Neutralinojs app. I am closing the issue since the issue is fixed. Thanks :tada:

**Closed by shalithasuranga** 2023-10-28 06:24 UTC
