### ISSUE TITLE
Check and improve plugin system

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs-cli#83] opened 2021-12-14 15:46 UTC
Now the plugins will disappear if the user upgrades the CLI. Try to check and improve this behavior

**Comment by pathange-s** [comment] 2022-03-26 05:44
@shalithasuranga I was successfully able to reproduce this issue. 

After update :

![image](https://user-images.githubusercontent.com/76244077/160226569-34d245a3-5aa0-4123-9174-2d120362873c.png)

**Comment by pathange-s** [comment] 2022-03-28 16:54
Was able to identify the issue.
- After installing a plugin, `neu.json` gets updated with the plugin name in the object. And, `node_modules` of the plugin are downloaded and `package.json` gets updated
- After updating neu-cli, `neu.json` has the plugin name in it. But `node_modules` and entry in `package.json` is deleted. If I install the plugin as : `npm install --save <plugin_name>` in the source directory, the plugin gets loaded successfully without the need to re run `neu plugins --add <plugin_name> `

So, due to absence of `node_modules` and entry in `package.json` this error arises.
I see that this issue is assigned to @shalithasuranga but has been left unresolved since long. Assign me the issue, while I start to fix it.

**Comment by pathange-s** [comment] 2022-03-28 19:24
The error throwing line is [this](https://github.com/neutralinojs/neutralinojs-cli/blob/acb969ce66281e4e58602c4279ebfe9dd645e076/src/plugins/pluginloader.js#L15). As this searches for the package name from `node_modules`

**Closed** 2022-05-02 10:18 UTC
Labels: enhancement
