### ISSUE TITLE
--frontend-lib-dev does not work with Vue 3 app 

### ISSUE THREAD

**Issue by MichaelNZ85** [neutralinojs/neutralinojs-cli#131] opened 2022-04-05 10:52 UTC
I followed the guidelines [here](https://neutralino.js.org/docs/how-to/use-a-frontend-library/) and successfully set up a React app running Neutralino and successfully hot-reloading. Upon following a similar process for Vue 3, I managed to run the app with Neutralino using `npm run dev`, but the hot reload failed with the error described below.

### Actual Behaviour
Running `neu run --frontend-lib-dev` with the Vue frontend running on port 3000 throws the following error:
```
/Users/myaccount/.nvm/versions/node/v16.14.2/lib/node_modules/@neutralinojs/neu/src/modules/frontendlib.js:16
        .replace(/\\/g, '/'); //Fix path on windows;
        ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at makeClientLibUrl (/Users/myaccount/.nvm/versions/node/v16.14.2/lib/node_modules/@neutralinojs/neu/src/modules/frontendlib.js:16:9)
    at async Object.module.exports.bootstrap (/Users/myaccount/.nvm/versions/node/v16.14.2/lib/node_modules/@neutralinojs/neu/src/modules/frontendlib.js:44:24)
```
The actual app displays the following error message also:
```
URI malformed

    at decodeURI (<anonymous>)
    at viteTransformMiddleware ([/Volumes/MacSSD2/Projects/neutralinojs/myapp/myapp-vue/node_modules/vite/dist/node/chunks/dep-611778e0.js:55639:19]())
    at call ([/Volumes/MacSSD2/Projects/neutralinojs/myapp/myapp-vue/node_modules/vite/dist/node/chunks/dep-611778e0.js:41437:7]())
    at next ([/Volumes/MacSSD2/Projects/neutralinojs/myapp/myapp-vue/node_modules/vite/dist/node/chunks/dep-611778e0.js:41381:5]())
    at [/Volumes/MacSSD2/Projects/neutralinojs/myapp/myapp-vue/node_modules/vite/dist/node/chunks/dep-611778e0.js:54726:28]()
    at viteServePublicMiddleware ([/Volumes/MacSSD2/Projects/neutralinojs/myapp/myapp-vue/node_modules/vite/dist/node/chunks/dep-611778e0.js:55231:9]())
    at call ([/Volumes/MacSSD2/Projects/neutralinojs/myapp/myapp-vue/node_modules/vite/dist/node/chunks/dep-611778e0.js:41437:7]())
    at next ([/Volumes/MacSSD2/Projects/neutralinojs/myapp/myapp-vue/node_modules/vite/dist/node/chunks/dep-611778e0.js:41381:5]())
    at next ([/Volumes/MacSSD2/Projects/neutralinojs/myapp/myapp-vue/node_modules/vite/dist/node/chunks/dep-611778e0.js:41359:14]())
    at next ([/Volumes/MacSSD2/Projects/neutralinojs/myapp/myapp-vue/node_modules/vite/dist/node/chunks/dep-611778e0.js:4]()'
```

### Expected Behaviour
The app should compile and run correctly, as the React app does.

**Comment by pathange-s** [comment] 2022-04-05 11:36
@MichaelNZ85 can you please give the necessary steps to reproduce the error, with OS and version details ? I guess the error statement itself explains it.

**Comment by pathange-s** [comment] 2022-04-05 19:09
@MichaelNZ85 Cool ! I was able to reproduce the error.

Let me explain why this occured:

```
async function makeClientLibUrl(port) {
    let configObj = config.get();
    let resourcesPath = configObj.cli.resourcesPath.replace(/^\//, '');
    let files = await recursive(resourcesPath);
    let clientLib = files
        .find((file) => /neutralino\.js$/.test(file))
        .replace(/\\/g, '/'); //Fix path on windows;

    let url = `http://localhost:${port}`;

    if(clientLib) {
        clientLib = '/' + clientLib;
        if(configObj.documentRoot) {
            clientLib = clientLib.replace(configObj.documentRoot, '/');
        }
        url += clientLib;
    }
    return url;
}
```
In this function, `files` array has all the paths for all files in path = `resourcePath`. Now `clientLib` iterates over all these paths to find the path for the file `neutralino.js` in files array.

Now, since your `veu` project doesnt have any file `neutralino.js`, .replace is run on undefined. Hence the error
`TypeError: Cannot read properties of undefined (reading 'replace')`
But in react app, under `resourcePath` you have a file `neutralino.js` ie `resources/js/neutralino.js` exists, and the process executes finely.|

Hope you understood why the error occurred. To solve this error, can you please provide me with some `vue` template ? I have no great experience with it.

**Comment by pathange-s** [comment] 2022-04-05 19:15
@shalithasuranga I see that there's a comment on [this](https://github.com/neutralinojs/neutralinojs-cli/blob/35d70ea9238abf27f270bfdbe63cb027f2d4c89e/src/modules/frontendlib.js#L16) line. May I know what was expected to be fixed ?

The path `resources\\js\\neutralino.js` is converted to `resources/js/neutralino.js` on windows wile on linux, `resources/js/neutralino.js` remails `resources/js/neutralino.js`

**Comment by shalithasuranga** [comment] 2023-10-28 06:32
Closing this since now developers can use the NPM module for using Neutralinojs API via `@neutralinojs/lib`. This issue won't occur since now we don't seek for paths for patching HTML files. Thanks for reporting and discussing :tada:

**Closed by shalithasuranga** 2023-10-28 06:32 UTC
